// <auto-generated />
using MaxShoes.Shop.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaxShoes.Shop.Identity.Migrations
{
    [DbContext(typeof(ApplicationIdentityDbContext))]
    partial class ApplicationIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MaxShoes.Shop.Identity.Models.UserModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            Email = "Employee1@test.pl",
                            IsEmailConfirmed = true,
                            Password = "$2a$11$IzNufv5QLYjULiVc5QZ/IOOIqAliQcnlcaBUUWsCG2TcSIEqn02Y.",
                            Role = "Employee",
                            UserName = "Employee1"
                        },
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f61",
                            Email = "Employee2@test.pl",
                            IsEmailConfirmed = true,
                            Password = "$2a$11$mY.v4l46HY3gesrHQJVxzuSAovZaihgAd4qUj/3yC5FrTvbYbjxp2",
                            Role = "Employee",
                            UserName = "Employee2"
                        });
                });

            modelBuilder.Entity("MaxShoes.Shop.Identity.Models.UserModels.User", b =>
                {
                    b.OwnsOne("MaxShoes.Shop.Application.Models.UserModels.Contact", "Contact", b1 =>
                        {
                            b1.Property<string>("UserId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("ApartmentNumber")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FirstName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("HouseNumber")
                                .HasColumnType("int");

                            b1.Property<string>("Id")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("State")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.HasData(
                                new
                                {
                                    UserId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                                    ApartmentNumber = 23,
                                    City = "Czestochowa",
                                    FirstName = "Piter",
                                    HouseNumber = 45,
                                    Id = "886c5a83-e232-4b8a-8e29-dac66b6f9cef",
                                    LastName = "Blukacz",
                                    PhoneNumber = "666111222",
                                    State = "Polska",
                                    Street = "Zielona",
                                    ZipCode = "42-200"
                                },
                                new
                                {
                                    UserId = "37846734-172e-4149-8cec-6f43d1eb3f61",
                                    ApartmentNumber = 0,
                                    City = "Czestochowa",
                                    FirstName = "Jan",
                                    HouseNumber = 2,
                                    Id = "c4b013ea-cf54-40ef-94a7-8d8e508031e6",
                                    LastName = "Oko",
                                    PhoneNumber = "666111223",
                                    State = "Polska",
                                    Street = "Liliowa",
                                    ZipCode = "42-202"
                                });
                        });

                    b.Navigation("Contact");
                });
#pragma warning restore 612, 618
        }
    }
}
